resolver: lts-20.8

packages:
- .

extra-deps:
- wasm-1.1.1@sha256:cea1e6c43d1ee46392eabb6b0f4fc469b6d8b987bcfbdd4694f9c48be346f229,2432

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []
